### ISSUE TITLE
REmove random constants from the code

### ISSUE THREAD

**Issue by fan1x** [Desperadus/CPP-zapoctak-evoluce#3]

**Comment by fan1x** [comment]
Also, put all the contants into a class where they belong, e.g. https://github.com/Desperadus/CPP-zapoctak-evoluce/blob/main/main.cpp#L28

**Comment by fan1x** [comment]
and make them `const`, e..g, 
```
nt WINDOW_WIDTH_GUI = 750;
int WINDOW_HEIGHT_GUI = 700;

int WINDOW_WIDTH_GAME = 930; 
int WINDOW_HEIGHT_GAME = 930; 

//default ingame settings
int ORGANISM_SIZE = 8;
int ORGANISM_SPEED = 1;

int ORGANISM_MAX_SIZE = 10;
int ORGANISM_MAX_SPEED = 10;

int NUMBER_OF_ORGANISMS = 50;
int NUMBER_OF_FOOD = 5500;
int NUMBER_OF_LINES = 7;
int NUMBER_OF_ANTIBIOTIC = 1000;

int ORGANISM_ENERGY = 200;
int REPRODUCTION_ENERGY = 300;
int FOOD_ENERGY = 5;
int RAND_FOOD_ENERGY = 4;
int ANTIBIOTIC_ENERGY = 3;
int ANTIBIOTIC_SIZE = 2;
int FOOD_SIZE = 2;
```

**Comment by Desperadus** [comment]
> and make them `const`, e..g,
> 
> ```
> nt WINDOW_WIDTH_GUI = 750;
> int WINDOW_HEIGHT_GUI = 700;
> 
> int WINDOW_WIDTH_GAME = 930; 
> int WINDOW_HEIGHT_GAME = 930; 
> 
> //default ingame settings
> int ORGANISM_SIZE = 8;
> int ORGANISM_SPEED = 1;
> 
> int ORGANISM_MAX_SIZE = 10;
> int ORGANISM_MAX_SPEED = 10;
> 
> int NUMBER_OF_ORGANISMS = 50;
> int NUMBER_OF_FOOD = 5500;
> int NUMBER_OF_LINES = 7;
> int NUMBER_OF_ANTIBIOTIC = 1000;
> 
> int ORGANISM_ENERGY = 200;
> int REPRODUCTION_ENERGY = 300;
> int FOOD_ENERGY = 5;
> int RAND_FOOD_ENERGY = 4;
> int ANTIBIOTIC_ENERGY = 3;
> int ANTIBIOTIC_SIZE = 2;
> int FOOD_SIZE = 2;
> ```

There is a reason they are not const. I want user to be able to change them via the GUI, they are not constants in reality - more like variables. Not all are changeable via the GUI as i thought some of them are rather boring ones, nevertheless one can opt out to add them in the GUI for change.
